name: Build Single Tree-sitter Parser

on:
  workflow_dispatch:
    inputs:
      language:
        description: "Language to build parser for"
        required: true
        type: choice
        options:
          - all
          - javascript
          - typescript
          - tsx
          - html
          - css
          - angular
          - java
          - kotlin
          - scala
          - python
          - go
          - rust
          - c-sharp
          - cpp
          - c
          - php
          - ruby
          - elixir
      platforms:
        description: "Platforms to build for"
        required: true
        type: choice
        default: "all"
        options:
          - all
          - linux-only
          - macos-only
          - windows-only

env:
  TREE_SITTER_ABI_VERSION: "15"

jobs:
  setup:
    name: Setup Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup matrix
        id: setup-matrix
        run: |
          # Define platform configurations
          platforms='[
            {"os": "ubuntu-latest", "arch": "x64", "platform": "linux"},
            {"os": "ubuntu-latest", "arch": "arm64", "platform": "linux"},
            {"os": "macos-latest", "arch": "x64", "platform": "darwin"},
            {"os": "macos-latest", "arch": "arm64", "platform": "darwin"},
            {"os": "windows-latest", "arch": "x64", "platform": "win32"}
          ]'

          if [ "${{ inputs.language }}" == "all" ]; then
            # Extract all language names from languages.json
            languages=$(jq -r '.languages | keys' languages.json)
          else
            # Single language
            languages='["${{ inputs.language }}"]'
          fi

          # Create matrix combinations
          matrix=$(echo "$languages" | jq -c --argjson platforms "$platforms" '[.[] as $lang | $platforms[] | . + {"language": $lang}]')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.language }} on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM64 on Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Set up tree-sitter CLI
        uses: tree-sitter/setup-action/cli@v2

      - name: Extract language info
        id: lang-info
        shell: bash
        run: |
          repo_url=$(jq -r ".languages[\"${{ matrix.language }}\"].repo" languages.json)
          ref=$(jq -r ".languages[\"${{ matrix.language }}\"].ref" languages.json)
          echo "repo_url=$repo_url" >> $GITHUB_OUTPUT
          echo "ref=$ref" >> $GITHUB_OUTPUT

      - name: Make scripts executable
        shell: bash
        run: chmod +x scripts/*.sh

      - name: Build parser (Linux ARM64)
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace \
            --platform linux/arm64 \
            node:18-alpine \
            sh -c "
              apk add --no-cache git bash tree-sitter-cli build-base &&
              ./scripts/build-parser.sh '${{ matrix.language }}' '${{ steps.lang-info.outputs.repo_url }}' '${{ steps.lang-info.outputs.ref }}' 'artifacts'
            "
        env:
          TREE_SITTER_ABI_VERSION: ${{ env.TREE_SITTER_ABI_VERSION }}

      - name: Build parser (Native)
        if: matrix.os != 'ubuntu-latest' || matrix.arch != 'arm64'
        shell: bash
        run: |
          ./scripts/build-parser.sh "${{ matrix.language }}" "${{ steps.lang-info.outputs.repo_url }}" "${{ steps.lang-info.outputs.ref }}" "artifacts"
        env:
          TREE_SITTER_ABI_VERSION: ${{ env.TREE_SITTER_ABI_VERSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parser-${{ matrix.language }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: artifacts/
          retention-days: 7

  upload:
    name: Upload to S3
    needs: build
    runs-on: ubuntu-latest
    if: always() && needs.build.result == 'success'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts-download/
          pattern: parser-*-*
          merge-multiple: true

      - name: Configure AWS Credentials for S3 Upload
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload parsers to S3
        run: |
          # Upload all parser files to S3
          find artifacts-download/ -type f \( -name "*.so" -o -name "*.dylib" -o -name "*.dll" -o -name "*.wasm" \) | while read -r file; do
            # Extract the relative path from artifacts directory
            relative_path=${file#artifacts-download/}
            
            # Construct S3 key
            s3_key="tree-sitter/parsers/tree-sitter-$relative_path"
            
            echo "Uploading: $file -> s3://${{ secrets.S3_BUCKET_NAME }}/$s3_key"
            
            # Upload to S3
            aws s3 cp "$file" "s3://${{ secrets.S3_BUCKET_NAME }}/$s3_key" \
              --metadata "source-file=$relative_path" \
              --cache-control "public, max-age=31536000" \
              --content-type "application/octet-stream"
          done

      - name: Summary
        run: |
          if [ "${{ inputs.language }}" == "all" ]; then
            echo "## 🎉 Build Summary for All Languages" >> $GITHUB_STEP_SUMMARY
          else
            echo "## 🎉 Build Summary for ${{ inputs.language }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Built Files" >> $GITHUB_STEP_SUMMARY
          find artifacts-download/ -name "*.so" -o -name "*.dylib" -o -name "*.dll" -o -name "*.wasm" | sort | while read file; do
            echo "- \`$(basename "$file")\` ($(du -h "$file" | cut -f1))" >> $GITHUB_STEP_SUMMARY
          done
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### S3 Location" >> $GITHUB_STEP_SUMMARY
          if [ "${{ inputs.language }}" == "all" ]; then
            echo "Files uploaded to: \`s3://${{ secrets.S3_BUCKET_NAME }}/tree-sitter/parsers/\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "Files uploaded to: \`s3://${{ secrets.S3_BUCKET_NAME }}/tree-sitter/parsers/tree-sitter-${{ inputs.language }}/\`" >> $GITHUB_STEP_SUMMARY
          fi
